version: '3'

networks:
  reiport-backend-network:
    driver: bridge

services:

  api:
    container_name: reiport-backend
    image: reiport-backend-img
    build: .
    ports:
    - 8080:3000
    restart: always
    depends_on:
      - reiport-redis
    networks:
      - reiport-backend-network

  reiport-redis:
    container_name: reiport-redis
    image: redis/redis-stack:latest
    restart: always
    networks:
      - reiport-backend-network

 