jwt:
  secret: cavascallahan
spring:
  thymeleaf:
    check-template-location: false
  mail:
    host: smtp.mailtrap.io
    username: 57f1cab5e78d26
    password: 768314b65dd096
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 25
          auth: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect